# Generated by Django 5.1.1 on 2024-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=122)),
                ("LastName", models.CharField(max_length=122)),
                ("Email", models.EmailField(max_length=122)),
                ("reemail", models.EmailField(max_length=122)),
                ("mobileno", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("repassword", models.CharField(max_length=20)),
            ],
        ),
    ]
