# Generated by Django 5.1.1 on 2024-10-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_sign"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Signup",
        ),
        migrations.AlterField(
            model_name="sign",
            name="FirstName",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="sign",
            name="LastName",
            field=models.TextField(),
        ),
    ]
