# Generated by Django 5.1.1 on 2024-10-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_sign_firstname_alter_sign_lastname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sign",
            old_name="firstName",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="sign",
            old_name="lastName",
            new_name="lastname",
        ),
    ]
