# Generated by Django 5.1.1 on 2024-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="username",
            field=models.EmailField(max_length=122),
        ),
    ]
