# Generated by Django 5.1.1 on 2024-10-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_login_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
    ]
