# Generated by Django 5.1.1 on 2024-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_delete_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sign",
            name="Email",
            field=models.EmailField(max_length=122, unique=True),
        ),
    ]
