# Generated by Django 5.1.1 on 2024-10-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_sign_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctername", models.CharField(max_length=122)),
                ("timeslot", models.CharField(max_length=122)),
            ],
        ),
    ]
