# Generated by Django 5.1.1 on 2024-10-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="username",
            field=models.CharField(default="omkar", max_length=122),
            preserve_default=False,
        ),
    ]
